### ISSUE TITLE
The Installation guidelines are missing for MS VS. 

### ISSUE THREAD

**Issue by AmasiaNalbandian** [JerryHue/yassgy#6]
I have dont have rust environment. The setup required that I have Microsoft Visual Studio, and then ensure I have the C++ Build tools before proceeding. This step was missing in the instructions.

**Comment by JerryHue** [comment]
Indeed, this is something that I overlooked. The requirements for setting up `rustup` in a Windows environment are slightly different, due to Rust depending on the MSVC compiler when installing in Windows.

I will make a subsection to differentiate between Windows and Linux environments. We would need to wait for a Mac user to let us know how different the setup for `rustup` is...

**Comment by AmasiaNalbandian** [comment]
I believe Mac users get stuck with the Terminal "app" which runs in bash shell. Basically the terminal is UNIX, and Linux inherits UNIX Compatibility - so should be same steps. :) I had a Mac before.
